In [2]:
import numpy as np

In [4]:
A=np.array([[7,2],[3,4],[5,3]])
A

array([[7, 2],
       [3, 4],
       [5, 3]])

In [5]:
u,s,v=np.linalg.svd(A)

In [6]:
u.shape

(3, 3)

In [7]:
s.shape

(2,)

In [8]:
v.shape

(2, 2)

In [9]:
np.dot(np.dot(u[:,:2],np.diag(s)),v)

array([[7., 2.],
       [3., 4.],
       [5., 3.]])

In [10]:
A

array([[7, 2],
       [3, 4],
       [5, 3]])

In [11]:
np.diag(A)

array([7, 4])

In [14]:
a1=np.dot(np.dot(u[:,:1],s[0]),v[:1,:])
a1

array([[6.26013786, 3.37310746],
       [3.99532758, 2.15277516],
       [5.12773272, 2.76294131]])

In [13]:
A

array([[7, 2],
       [3, 4],
       [5, 3]])

In [17]:
s[0]/np.sum(s)

0.7959317231047445

In [18]:
s[1]/np.sum(s)

0.20406827689525547

In [19]:
# 20 percent is the lose

In [21]:
A=np.array([[1,1,1,0,0],
            [3,3,3,0,0],
            [4,4,4,0,0],
            [5,5,5,0,0],
            [0,2,0,4,4],
            [0,0,0,5,5],
            [0,1,0,2,2]])
A

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 2, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 1, 0, 2, 2]])

In [23]:
u,s,v=np.linalg.svd(A)

In [24]:
u.shape

(7, 7)

In [25]:
s.shape

(5,)

In [26]:
v.shape

(5, 5)

In [27]:
s.round(3)

array([12.481,  9.509,  1.346,  0.   ,  0.   ])

In [30]:
red_A=np.dot(np.dot(u[:,:3],np.diag(s[:3])),v[:3,:])
red_A.round(3)

array([[ 1.,  1.,  1.,  0.,  0.],
       [ 3.,  3.,  3., -0., -0.],
       [ 4.,  4.,  4.,  0.,  0.],
       [ 5.,  5.,  5.,  0.,  0.],
       [-0.,  2.,  0.,  4.,  4.],
       [ 0.,  0.,  0.,  5.,  5.],
       [-0.,  1.,  0.,  2.,  2.]])

In [32]:
import pandas as pd
A1=pd.DataFrame(A,columns=['m1','m2','m3','m4','m5'],index=['u1','u2','u3','u4','u5','u6','u7'])

In [33]:
A1

m1  m2  m3  m4  m5
u1   1   1   1   0   0
u2   3   3   3   0   0
u3   4   4   4   0   0
u4   5   5   5   0   0
u5   0   2   0   4   4
u6   0   0   0   5   5
u7   0   1   0   2   2

In [35]:
pd.DataFrame(u[:,:2].round(2),columns=['concept1','concept2'],index=['u1','u2','u3','u4','u5','u6','u7'])

concept1  concept2
u1     -0.14     -0.02
u2     -0.41     -0.07
u3     -0.55     -0.09
u4     -0.69     -0.12
u5     -0.15      0.59
u6     -0.07      0.73
u7     -0.08      0.30

In [36]:
df=pd.read_csv('bcancer.csv')
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [37]:
inp=df.drop('diagnosis',axis=1)

In [38]:
out=df['diagnosis']

In [39]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(inp,out,test_size=0.3,random_state=48)

In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [42]:
rf=RandomForestClassifier(random_state=0)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
print('without any dimensionality reduction')
print('the number of features are:',inp.shape[1])
print('#######################################')
print(classification_report(ytest,ypred))

without any dimensionality reduction
the number of features are: 30
#######################################
              precision    recall  f1-score   support

           B       0.94      0.95      0.94        95
           M       0.93      0.92      0.93        76

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



In [43]:
# scalling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
inp_sc=sc.fit_transform(inp)

In [47]:
inp_sc=pd.DataFrame(inp_sc)

In [48]:
inp_sc.head()

0         1         2         3         4         5         6   \
0  1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   
1  1.829821 -0.353632  1.685955  1.908708 -0.826962 -0.487072 -0.023846   
2  1.579888  0.456187  1.566503  1.558884  0.942210  1.052926  1.363478   
3 -0.768909  0.253732 -0.592687 -0.764464  3.283553  3.402909  1.915897   
4  1.750297 -1.151816  1.776573  1.826229  0.280372  0.539340  1.371011   

         7         8         9   ...        20        21        22        23  \
0  2.532475  2.217515  2.255747  ...  1.886690 -1.359293  2.303601  2.001237   
1  0.548144  0.001392 -0.868652  ...  1.805927 -0.369203  1.535126  1.890489   
2  2.037231  0.939685 -0.398008  ...  1.511870 -0.023974  1.347475  1.456285   
3  1.451707  2.867383  4.910919  ... -0.281464  0.133984 -0.249939 -0.550021   
4  1.428493 -0.009560 -0.562450  ...  1.298575 -1.466770  1.338539  1.220724   

         24        25        26        27        28        29  
0  1.307686  2.616665  2.109526  2.296076  2.750622  1.937015  
1 -0.375612 -0.430444 -0.146749  1.087084 -0.243890  0.281190  
2  0.527407  1.082932  0.854974  1.955000  1.152255  0.201391  
3  3.394275  3.893397  1.989588  2.175786  6.046041  4.935010  
4  0.220556 -0.313395  0.613179  0.729259 -0.868353 -0.397100  

[5 rows x 30 columns]

In [49]:
from sklearn.decomposition import PCA
pc=PCA()
pca_inp=pc.fit_transform(inp_sc)

In [50]:
inp_sc.shape,pca_inp.shape

((569, 30), (569, 30))

In [52]:
pca_inp=pd.DataFrame(pca_inp)

In [53]:
pca_inp.head()

0          1         2         3         4         5         6   \
0  9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159370   
1  2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013358   
2  5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668166   
3  7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053422  1.429911   
4  3.935302  -1.948072  1.389767  2.940639  0.546747 -1.226495 -0.936213   

         7         8         9   ...        20        21        22        23  \
0 -0.398407 -0.157118 -0.877402  ...  0.096515  0.068850  0.084519 -0.175256   
1  0.240988 -0.711905  1.106995  ... -0.077327 -0.094578 -0.217718  0.011290   
2  0.097374  0.024066  0.454275  ...  0.311067 -0.060309 -0.074291  0.102762   
3  1.059565 -1.405440 -1.116975  ...  0.434193 -0.203266 -0.124105  0.153430   
4  0.636376 -0.263805  0.377704  ... -0.116545 -0.017650  0.139454 -0.005332   

         24        25        26        27        28        29  
0 -0.151020 -0.201503 -0.252585 -0.033914  0.045648 -0.047169  
1 -0.170510 -0.041129  0.181270  0.032624 -0.005687 -0.001868  
2  0.171158  0.004735  0.049569  0.047026  0.003146  0.000751  
3  0.077496 -0.275225  0.183462  0.042484 -0.069295 -0.019937  
4  0.003062  0.039254  0.032168 -0.034786  0.005038  0.021214  

[5 rows x 30 columns]

In [56]:
# eigen values
pd.DataFrame(pc.explained_variance_).round()

0
0   13.0
1    6.0
2    3.0
3    2.0
4    2.0
5    1.0
6    1.0
7    0.0
8    0.0
9    0.0
10   0.0
11   0.0
12   0.0
13   0.0
14   0.0
15   0.0
16   0.0
17   0.0
18   0.0
19   0.0
20   0.0
21   0.0
22   0.0
23   0.0
24   0.0
25   0.0
26   0.0
27   0.0
28   0.0
29   0.0

In [58]:
# ratio how much the feature is captured
pd.DataFrame(pc.explained_variance_ratio_).round(2)

0
0   0.44
1   0.19
2   0.09
3   0.07
4   0.05
5   0.04
6   0.02
7   0.02
8   0.01
9   0.01
10  0.01
11  0.01
12  0.01
13  0.01
14  0.00
15  0.00
16  0.00
17  0.00
18  0.00
19  0.00
20  0.00
21  0.00
22  0.00
23  0.00
24  0.00
25  0.00
26  0.00
27  0.00
28  0.00
29  0.00

In [55]:
cum_var=np.cumsum(pc.explained_variance_ratio_)
# number of features to select
(cum_var<0.95).sum()

9

In [65]:
pca_inp_red=pca_inp.iloc[:,:9]

In [66]:
pca_inp_red.shape

(569, 9)

In [67]:

xtrain,xtest,ytrain,ytest=train_test_split(pca_inp_red,out,test_size=0.3,random_state=48)


In [87]:

rf=RandomForestClassifier(random_state=0)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
print('with PCA reduction')
print('the number of features are:',inp.shape[1])
print('#######################################')
print(classification_report(ytest,ypred))

with PCA reduction
the number of features are: 30
#######################################
              precision    recall  f1-score   support

           B       0.94      0.96      0.95        95
           M       0.95      0.92      0.93        76

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171



In [76]:
from sklearn.decomposition import TruncatedSVD
sv=TruncatedSVD(n_components=30)
svd_inp=sv.fit_transform(inp_sc)

In [77]:
inp_sc.shape,svd_inp.shape

((569, 30), (569, 30))

In [78]:
cum_var=np.cumsum(sv.explained_variance_ratio_)
# number of features to select
(cum_var<0.95).sum()

9

In [82]:
svd_inp=pd.DataFrame(svd_inp)

In [83]:
svd_inp_red=svd_inp.iloc[:,:9]

In [84]:

xtrain,xtest,ytrain,ytest=train_test_split(svd_inp_red,out,test_size=0.3,random_state=36)


In [89]:

rf_mod=RandomForestClassifier(random_state=36)
rf_mod.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
print('with SVD component reduction')
print('the number of features are:',xtrain.shape[1])
print('#######################################')
print(classification_report(ytest,ypred))

with SVD component reduction
the number of features are: 9
#######################################
              precision    recall  f1-score   support

           B       0.92      0.94      0.93        95
           M       0.92      0.89      0.91        76

    accuracy                           0.92       171
   macro avg       0.92      0.92      0.92       171
weighted avg       0.92      0.92      0.92       171

